export const ROLES = {
  EMPLOYEE: 'employee',
  PM: 'pm',
  CREATIVE_MANAGER: 'creative_manager',
  CREATIVE_HEAD: 'creative_head',
  HEAD: 'head',
  ADMIN: 'admin',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_LABELS: Record<Role, string> = {
  [ROLES.EMPLOYEE]: 'Employee',
  [ROLES.PM]: 'Project Manager',
  [ROLES.CREATIVE_MANAGER]: 'Creative Manager',
  [ROLES.CREATIVE_HEAD]: 'Creative Head',
  [ROLES.HEAD]: 'Department Head',
  [ROLES.ADMIN]: 'Admin',
};

/** Column order for the permission matrix (least → most privileged). */
export const ROLE_ORDER: Role[] = [
  ROLES.EMPLOYEE,
  ROLES.PM,
  ROLES.CREATIVE_MANAGER,
  ROLES.CREATIVE_HEAD,
  ROLES.HEAD,
  ROLES.ADMIN,
];

export const PERMISSIONS = {
  // Task & Project
  MANAGE_PROJECTS: [ROLES.PM, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  EDIT_PROJECT: [ROLES.PM, ROLES.HEAD, ROLES.ADMIN],
  ASSIGN_TASK: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD],
  REVIEW_CREATIVE_TASK: [ROLES.CREATIVE_HEAD],
  VIEW_ALL_TASKS: [
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],
  EVALUATE_TASK: [ROLES.PM, ROLES.HEAD, ROLES.ADMIN],

  // Capacity & Workload
  VIEW_CAPACITY: [ROLES.HEAD, ROLES.ADMIN, ROLES.PM],
  VIEW_CAPACITY_FULL: [ROLES.HEAD, ROLES.ADMIN],
  VIEW_WORKLOAD: [
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],

  // Performance & KPI
  VIEW_PERFORMANCE: [ROLES.HEAD, ROLES.ADMIN],
  EDIT_KPI_SETTINGS: [ROLES.HEAD, ROLES.ADMIN],

  // Quality
  VIEW_QUALITY: [ROLES.PM, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],

  // OT
  REQUEST_OT: [ROLES.PM, ROLES.CREATIVE_MANAGER],
  APPROVE_OT: [ROLES.HEAD, ROLES.ADMIN],

  // Reports
  EXPORT_REPORT: [ROLES.PM, ROLES.HEAD, ROLES.ADMIN],

  // Users & Admin
  MANAGE_USERS: [ROLES.ADMIN],
  MANAGE_TITLES: [ROLES.HEAD, ROLES.ADMIN],
  VIEW_AUDIT_LOG: [ROLES.ADMIN],
} as const;

export type Permission = keyof typeof PERMISSIONS;
