export const ROLES = {
  EMPLOYEE: 'employee',
  PM: 'pm',
  CREATIVE_MANAGER: 'creative_manager',
  CREATIVE_HEAD: 'creative_head',
  HEAD: 'head',
  ADMIN: 'admin',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_LABELS: Record<Role, string> = {
  [ROLES.EMPLOYEE]: 'Employee',
  [ROLES.PM]: 'Project Manager',
  [ROLES.CREATIVE_MANAGER]: 'Creative Manager',
  [ROLES.CREATIVE_HEAD]: 'Creative Head',
  [ROLES.HEAD]: 'Department Head',
  [ROLES.ADMIN]: 'Admin',
};

/** Column order for the permission matrix (least → most privileged). */
export const ROLE_ORDER: Role[] = [
  ROLES.EMPLOYEE,
  ROLES.PM,
  ROLES.CREATIVE_MANAGER,
  ROLES.CREATIVE_HEAD,
  ROLES.HEAD,
  ROLES.ADMIN,
];

export const PERMISSIONS = {
  // Task & Project
  // View: Employee included so they can open participated projects (brief / client knowledge).
  MANAGE_PROJECTS: [
    ROLES.EMPLOYEE,
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],
  // Create: Department Head (+ Admin) only — PM/CM/CH may edit but not create.
  CREATE_PROJECT: [ROLES.HEAD, ROLES.ADMIN],
  EDIT_PROJECT: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  ARCHIVE_PROJECT: [ROLES.HEAD, ROLES.ADMIN],
  DELETE_PROJECT: [ROLES.HEAD, ROLES.ADMIN],
  CREATE_TASK: [ROLES.PM, ROLES.ADMIN],
  ASSIGN_TASK: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  REVIEW_CREATIVE_TASK: [ROLES.CREATIVE_HEAD],
  // CM is scoped (assignee / CM ownership / assigned-by) — not org-wide.
  VIEW_ALL_TASKS: [ROLES.PM, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  EVALUATE_TASK: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],

  // Capacity & Workload
  VIEW_CAPACITY: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  VIEW_CAPACITY_FULL: [
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],
  VIEW_WORKLOAD: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],

  // Performance & KPI
  VIEW_PERFORMANCE: [
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],
  EDIT_KPI_SETTINGS: [
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],

  // Quality
  VIEW_QUALITY: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],

  // OT — approve is Head / Admin only (PM/CM/CH request + review results)
  REQUEST_OT: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  APPROVE_OT: [ROLES.HEAD, ROLES.ADMIN],

  // Reports
  EXPORT_REPORT: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],

  // Users & Admin
  VIEW_USER: [
    ROLES.EMPLOYEE,
    ROLES.PM,
    ROLES.CREATIVE_MANAGER,
    ROLES.CREATIVE_HEAD,
    ROLES.HEAD,
    ROLES.ADMIN,
  ],
  MANAGE_USERS: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  MANAGE_LEAVE: [ROLES.PM, ROLES.CREATIVE_MANAGER, ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  REACTIVATE_USER: [ROLES.ADMIN],
  MANAGE_TITLES: [ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  MANAGE_DEPARTMENTS: [ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  MANAGE_CLIENTS: [ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  MANAGE_TASK_SCORES: [ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
  VIEW_AUDIT_LOG: [ROLES.CREATIVE_HEAD, ROLES.HEAD, ROLES.ADMIN],
} as const;

export type Permission = keyof typeof PERMISSIONS;
